import type { ScheduledPost, ScheduledPostStatus } from '../types'

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

export const adminScheduledPostsKeys = {
  all: ['admin-scheduled-posts'] as const,
  user: (userId: string) => [...adminScheduledPostsKeys.all, 'user', userId] as const,
  team: (teamId: string) => [...adminScheduledPostsKeys.all, 'team', teamId] as const,
}

const mockUserPosts: Record<string, ScheduledPost[]> = {
  '1': [
    {
      id: 'sp1',
      platform: 'instagram',
      title: 'The 3 Steps to Launch a SaaS',
      description: 'Learn the essential steps to launch your SaaS product. #saas #startup',
      thumbnailUrl: 'https://picsum.photos/seed/sp1/360/640',
      status: 'published',
      scheduledAt: '2026-03-01T14:00:00Z',
      publishedAt: '2026-03-01T14:01:22Z',
      lastAttemptedAt: '2026-03-01T14:01:22Z',
      socialPublishId: 'ig_1001234567',
      retryCount: 0,
      errorMessage: null,
      projectResultId: '101',
      socialConnectionId: 'sc1',
      createdAt: '2026-02-28T10:00:00Z',
      updatedAt: '2026-03-01T14:01:22Z',
    },
    {
      id: 'sp2',
      platform: 'tiktok',
      title: 'Why Most SaaS Fail',
      description: 'Common mistakes that lead to SaaS failure. #saas #lessons',
      thumbnailUrl: 'https://picsum.photos/seed/sp2/360/640',
      status: 'published',
      scheduledAt: '2026-03-01T18:00:00Z',
      publishedAt: '2026-03-01T18:02:11Z',
      lastAttemptedAt: '2026-03-01T18:02:11Z',
      socialPublishId: 'tik_7391234567',
      retryCount: 0,
      errorMessage: null,
      projectResultId: '102',
      socialConnectionId: 'sc2',
      createdAt: '2026-02-28T09:00:00Z',
      updatedAt: '2026-03-01T18:02:11Z',
    },
    {
      id: 'sp3',
      platform: 'youtube',
      title: 'Pricing Strategy for SaaS',
      description: 'How to price your SaaS product for maximum revenue. #pricing #saas',
      thumbnailUrl: 'https://picsum.photos/seed/sp3/360/640',
      status: 'failed',
      scheduledAt: '2026-03-03T16:00:00Z',
      publishedAt: null,
      lastAttemptedAt: '2026-03-03T16:01:00Z',
      socialPublishId: null,
      retryCount: 3,
      errorMessage: 'Upload quota exceeded. Please try again later.',
      projectResultId: '103',
      socialConnectionId: 'sc3',
      createdAt: '2026-03-02T08:00:00Z',
      updatedAt: '2026-03-03T16:01:00Z',
    },
    {
      id: 'sp4',
      platform: 'instagram',
      title: 'Customer Acquisition Tips',
      description: 'Proven strategies to acquire your first 100 customers.',
      thumbnailUrl: 'https://picsum.photos/seed/sp4/360/640',
      status: 'published',
      scheduledAt: '2026-03-05T12:00:00Z',
      publishedAt: '2026-03-05T12:01:05Z',
      lastAttemptedAt: '2026-03-05T12:01:05Z',
      socialPublishId: 'ig_1009988776',
      retryCount: 0,
      errorMessage: null,
      projectResultId: '105',
      socialConnectionId: 'sc1',
      createdAt: '2026-03-04T09:00:00Z',
      updatedAt: '2026-03-05T12:01:05Z',
    },
    {
      id: 'sp5',
      platform: 'tiktok',
      title: 'Building an MVP Fast',
      description: 'How to build a minimum viable product in just 2 weeks. #mvp #startup',
      thumbnailUrl: 'https://picsum.photos/seed/sp5/360/640',
      status: 'published',
      scheduledAt: '2026-03-05T20:00:00Z',
      publishedAt: '2026-03-05T20:00:48Z',
      lastAttemptedAt: '2026-03-05T20:00:48Z',
      socialPublishId: 'tik_7401122334',
      retryCount: 0,
      errorMessage: null,
      projectResultId: '106',
      socialConnectionId: 'sc2',
      createdAt: '2026-03-04T14:00:00Z',
      updatedAt: '2026-03-05T20:00:48Z',
    },
    {
      id: 'sp6',
      platform: 'instagram',
      title: 'Fundraising for SaaS Startups',
      description: 'How to raise your seed round. #fundraising #vc #startup',
      thumbnailUrl: 'https://picsum.photos/seed/sp6/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-10T14:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '108',
      socialConnectionId: 'sc1',
      createdAt: '2026-03-06T10:00:00Z',
      updatedAt: '2026-03-06T10:00:00Z',
    },
    {
      id: 'sp7',
      platform: 'youtube',
      title: 'Tech Stack for Your SaaS',
      description: 'Best technologies to build a modern SaaS in 2026. #techstack #saas',
      thumbnailUrl: 'https://picsum.photos/seed/sp7/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-10T18:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '104',
      socialConnectionId: 'sc3',
      createdAt: '2026-03-06T11:00:00Z',
      updatedAt: '2026-03-06T11:00:00Z',
    },
    {
      id: 'sp8',
      platform: 'tiktok',
      title: 'Scaling Infrastructure',
      description: 'When and how to scale your SaaS infrastructure. #scaling #devops',
      thumbnailUrl: 'https://picsum.photos/seed/sp8/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-12T15:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '107',
      socialConnectionId: 'sc2',
      createdAt: '2026-03-06T12:00:00Z',
      updatedAt: '2026-03-06T12:00:00Z',
    },
    {
      id: 'sp9',
      platform: 'instagram',
      title: 'Customer Acquisition Tips - Part 2',
      description: 'More strategies to grow your SaaS customer base. #growth #saas',
      thumbnailUrl: 'https://picsum.photos/seed/sp9/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-15T12:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '105',
      socialConnectionId: 'sc1',
      createdAt: '2026-03-06T13:00:00Z',
      updatedAt: '2026-03-06T13:00:00Z',
    },
    {
      id: 'sp10',
      platform: 'youtube',
      title: 'SaaS Churn Analysis Deep Dive',
      description: 'How to reduce churn and increase retention. #churn #retention',
      thumbnailUrl: 'https://picsum.photos/seed/sp10/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-18T16:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '101',
      socialConnectionId: 'sc3',
      createdAt: '2026-03-06T14:00:00Z',
      updatedAt: '2026-03-06T14:00:00Z',
    },
    {
      id: 'sp11',
      platform: 'tiktok',
      title: 'The SaaS Pricing Mistake Everyone Makes',
      description: null,
      thumbnailUrl: 'https://picsum.photos/seed/sp11/360/640',
      status: 'pending',
      scheduledAt: null,
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '103',
      socialConnectionId: 'sc2',
      createdAt: '2026-03-06T15:00:00Z',
      updatedAt: '2026-03-06T15:00:00Z',
    },
    {
      id: 'sp12',
      platform: 'instagram',
      title: 'How We Hit 1000 Users',
      description: 'Our story from 0 to 1000 paying customers. #milestone #growth',
      thumbnailUrl: 'https://picsum.photos/seed/sp12/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-22T14:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '102',
      socialConnectionId: 'sc1',
      createdAt: '2026-03-06T16:00:00Z',
      updatedAt: '2026-03-06T16:00:00Z',
    },
    {
      id: 'sp13',
      platform: 'youtube',
      title: 'Hiring Your First Engineer',
      description: 'Tips for hiring your first technical employee at a SaaS startup.',
      thumbnailUrl: 'https://picsum.photos/seed/sp13/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-25T18:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '108',
      socialConnectionId: 'sc3',
      createdAt: '2026-03-06T17:00:00Z',
      updatedAt: '2026-03-06T17:00:00Z',
    },
    {
      id: 'sp14',
      platform: 'instagram',
      title: 'Monthly SaaS Recap - February',
      description: 'Our February metrics and what we learned. #transparency #saas',
      thumbnailUrl: 'https://picsum.photos/seed/sp14/360/640',
      status: 'cancelled',
      scheduledAt: '2026-03-28T12:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '106',
      socialConnectionId: 'sc1',
      createdAt: '2026-03-05T10:00:00Z',
      updatedAt: '2026-03-06T08:00:00Z',
    },
  ],
  '2': [
    {
      id: 'sp15',
      platform: 'instagram',
      title: 'AI Will Change Everything',
      description: 'The most impactful prediction about AI from our expert panel.',
      thumbnailUrl: 'https://picsum.photos/seed/sp15/360/640',
      status: 'published',
      scheduledAt: '2026-03-02T18:00:00Z',
      publishedAt: '2026-03-02T18:01:30Z',
      lastAttemptedAt: '2026-03-02T18:01:30Z',
      socialPublishId: 'ig_8823456789',
      retryCount: 0,
      errorMessage: null,
      projectResultId: '201',
      socialConnectionId: 'sc4',
      createdAt: '2026-03-01T12:00:00Z',
      updatedAt: '2026-03-02T18:01:30Z',
    },
    {
      id: 'sp16',
      platform: 'tiktok',
      title: 'The Ethics of AI Development',
      description: 'Important ethical considerations when building AI systems. #aiethics',
      thumbnailUrl: 'https://picsum.photos/seed/sp16/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-14T20:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: '202',
      socialConnectionId: 'sc5',
      createdAt: '2026-03-06T09:00:00Z',
      updatedAt: '2026-03-06T09:00:00Z',
    },
  ],
}

const mockTeamPosts: Record<string, ScheduledPost[]> = {
  '1': [
    {
      id: 'tsp1',
      platform: 'instagram',
      title: 'Tutorial: Como usar o VDClip - Clip 1',
      description: 'Aprenda a usar o VDClip em minutos. #tutorial #vdclip',
      thumbnailUrl: 'https://picsum.photos/seed/tsp2/360/640',
      status: 'published',
      scheduledAt: '2026-03-03T14:00:00Z',
      publishedAt: '2026-03-03T14:00:45Z',
      lastAttemptedAt: '2026-03-03T14:00:45Z',
      socialPublishId: 'ig_9934567890',
      retryCount: 0,
      errorMessage: null,
      projectResultId: 'tm2',
      socialConnectionId: 'tsc2',
      createdAt: '2026-03-02T10:00:00Z',
      updatedAt: '2026-03-03T14:00:45Z',
    },
    {
      id: 'tsp2',
      platform: 'tiktok',
      title: 'Tutorial: Como usar o VDClip - Clip 2',
      description: 'Parte 2: recursos avancados do VDClip. #tutorial #vdclip',
      thumbnailUrl: 'https://picsum.photos/seed/tsp3/360/640',
      status: 'published',
      scheduledAt: '2026-03-03T20:00:00Z',
      publishedAt: '2026-03-03T20:01:12Z',
      lastAttemptedAt: '2026-03-03T20:01:12Z',
      socialPublishId: 'tik_8810293847',
      retryCount: 0,
      errorMessage: null,
      projectResultId: 'tm2',
      socialConnectionId: 'tsc3',
      createdAt: '2026-03-02T11:00:00Z',
      updatedAt: '2026-03-03T20:01:12Z',
    },
    {
      id: 'tsp3',
      platform: 'youtube',
      title: 'VDClip Product Demo 2026 - Highlights',
      description: 'See the best moments from our 2026 product demo. #vdclip #saas',
      thumbnailUrl: 'https://picsum.photos/seed/tsp1/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-08T15:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: 'tm1',
      socialConnectionId: 'tsc1',
      createdAt: '2026-03-06T09:00:00Z',
      updatedAt: '2026-03-06T09:00:00Z',
    },
    {
      id: 'tsp4',
      platform: 'instagram',
      title: 'VDClip Feature Showcase - Clips',
      description: 'All the new features we shipped in February. #product #vdclip',
      thumbnailUrl: 'https://picsum.photos/seed/tsp4/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-11T13:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: 'tm3',
      socialConnectionId: 'tsc2',
      createdAt: '2026-03-06T10:00:00Z',
      updatedAt: '2026-03-06T10:00:00Z',
    },
    {
      id: 'tsp5',
      platform: 'tiktok',
      title: 'VDClip Feature Showcase - Clip',
      description: null,
      thumbnailUrl: null,
      status: 'pending',
      scheduledAt: null,
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: null,
      socialConnectionId: 'tsc3',
      createdAt: '2026-03-06T11:30:00Z',
      updatedAt: '2026-03-06T11:30:00Z',
    },
    {
      id: 'tsp6',
      platform: 'youtube',
      title: 'Como o VDClip Processa seus Videos com IA',
      description: 'Veja como a nossa IA gera clips virais automaticamente. #ia #vdclip',
      thumbnailUrl: 'https://picsum.photos/seed/tsp6/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-17T16:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: 'tm1',
      socialConnectionId: 'tsc1',
      createdAt: '2026-03-06T12:00:00Z',
      updatedAt: '2026-03-06T12:00:00Z',
    },
    {
      id: 'tsp7',
      platform: 'instagram',
      title: 'Depoimento: Como a empresa X cresceu com VDClip',
      description: 'Case de sucesso de um dos nossos clientes. #casesucesso #vdclip',
      thumbnailUrl: 'https://picsum.photos/seed/tsp7/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-20T12:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: 'tm2',
      socialConnectionId: 'tsc2',
      createdAt: '2026-03-06T13:00:00Z',
      updatedAt: '2026-03-06T13:00:00Z',
    },
  ],
  '6': [
    {
      id: 'tsp8',
      platform: 'tiktok',
      title: 'Best Music Compilation 2026 - Top Clip',
      description: '#music #compilation #tiktok',
      thumbnailUrl: 'https://picsum.photos/seed/tsp8/360/640',
      status: 'published',
      scheduledAt: '2026-03-04T20:00:00Z',
      publishedAt: '2026-03-04T20:00:58Z',
      lastAttemptedAt: '2026-03-04T20:00:58Z',
      socialPublishId: 'tik_6672345678',
      retryCount: 0,
      errorMessage: null,
      projectResultId: 'tm6-1',
      socialConnectionId: 'tsc4',
      createdAt: '2026-03-03T16:00:00Z',
      updatedAt: '2026-03-04T20:00:58Z',
    },
    {
      id: 'tsp9',
      platform: 'instagram',
      title: 'Top Hits January Highlights - Clip 1',
      description: 'The best music moments of January. #music #highlights',
      thumbnailUrl: 'https://picsum.photos/seed/tsp9/360/640',
      status: 'scheduled',
      scheduledAt: '2026-03-13T18:00:00Z',
      publishedAt: null,
      lastAttemptedAt: null,
      socialPublishId: null,
      retryCount: 0,
      errorMessage: null,
      projectResultId: 'tm6-2',
      socialConnectionId: 'tsc5',
      createdAt: '2026-03-06T10:00:00Z',
      updatedAt: '2026-03-06T10:00:00Z',
    },
  ],
}

export function useAdminUserScheduledPosts(userId: string, enabled: boolean) {
  return useQuery({
    queryKey: adminScheduledPostsKeys.user(userId),
    queryFn: async () => {
      await new Promise((r) => setTimeout(r, 400))
      return mockUserPosts[userId] ?? []
    },
    enabled,
  })
}

export function useAdminTeamScheduledPosts(teamId: string, enabled: boolean) {
  return useQuery({
    queryKey: adminScheduledPostsKeys.team(teamId),
    queryFn: async () => {
      await new Promise((r) => setTimeout(r, 400))
      return mockTeamPosts[teamId] ?? []
    },
    enabled,
  })
}

export interface UpdateScheduledPostInput {
  title?: string
  description?: string | null
  scheduledAt?: string | null
  status?: ScheduledPostStatus
}

export function useUpdateScheduledPost(scope: 'user' | 'team', scopeId: string) {
  const queryClient = useQueryClient()
  const key =
    scope === 'user'
      ? adminScheduledPostsKeys.user(scopeId)
      : adminScheduledPostsKeys.team(scopeId)

  return useMutation({
    mutationFn: async ({ postId, data }: { postId: string; data: UpdateScheduledPostInput }) => {
      await new Promise((r) => setTimeout(r, 500))
      return { postId, data }
    },
    onSuccess: ({ postId, data }) => {
      queryClient.setQueryData<ScheduledPost[]>(key, (prev) =>
        prev?.map((p) =>
          p.id === postId ? { ...p, ...data, updatedAt: new Date().toISOString() } : p,
        ) ?? [],      )
    },
  })
}

export function useCancelScheduledPost(scope: 'user' | 'team', scopeId: string) {
  const queryClient = useQueryClient()
  const key =
    scope === 'user'
      ? adminScheduledPostsKeys.user(scopeId)
      : adminScheduledPostsKeys.team(scopeId)

  return useMutation({
    mutationFn: async (postId: string) => {
      await new Promise((r) => setTimeout(r, 400))
      return postId
    },
    onSuccess: (postId) => {
      queryClient.setQueryData<ScheduledPost[]>(key, (prev) =>
        prev?.map((p) =>
          p.id === postId
            ? { ...p, status: 'cancelled' as ScheduledPostStatus, updatedAt: new Date().toISOString() }
            : p,
        ) ?? [],      )
    },
  })
}
