import { useQuery } from '@tanstack/react-query'

import type { AdminMedia, MediaResult } from '../types'

export const adminMediaKeys = {
  all: ['admin-media'] as const,
  user: (userId: string) => [...adminMediaKeys.all, 'user', userId] as const,
  results: (mediaId: string) =>
    [...adminMediaKeys.all, 'results', mediaId] as const,
}

const mockMedia: Record<string, AdminMedia[]> = {
  '1': [
    {
      id: '1',
      title: 'How to Build a SaaS in 2024 - Complete Guide',
      url: 'https://youtube.com/watch?v=abc123',
      thumbnailUrl: 'https://picsum.photos/seed/m1/640/360',
      status: 'completed',
      aiType: 'clips',
      aspectRatio: '9:16',
      category: 'Education',
      language: 'en',
      provider: 'youtube',
      processStep: 5,
      clipLengths: ['30-60', '60-90'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 8,
    },
    {
      id: '2',
      title: 'Podcast Episode #45 - The Future of AI',
      url: 'https://youtube.com/watch?v=def456',
      thumbnailUrl: 'https://picsum.photos/seed/m2/640/360',
      status: 'completed',
      aiType: 'highlights',
      aspectRatio: 'auto',
      category: 'Podcast',
      language: 'en',
      provider: 'youtube',
      processStep: 5,
      clipLengths: ['60-120'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 3,
    },
    {
      id: '3',
      title: 'React 19 New Features Explained',
      url: 'https://twitch.tv/videos/xyz',
      thumbnailUrl: 'https://picsum.photos/seed/m3/640/360',
      status: 'processing',
      aiType: 'shorts',
      aspectRatio: '9:16',
      category: 'Technology',
      language: 'pt',
      provider: 'twitch',
      processStep: 2,
      clipLengths: ['15-30'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 0,
    },
    {
      id: '4',
      title: 'Live Coding Session - Building a Dashboard',
      url: 'https://twitch.tv/videos/abc',
      thumbnailUrl: 'https://picsum.photos/seed/m4/640/360',
      status: 'failed',
      aiType: 'clips',
      aspectRatio: '16:9',
      category: 'Gaming',
      language: 'en',
      provider: 'twitch',
      processStep: 3,
      clipLengths: ['30-60', '60-90'],
      errorCode: 'TRANSCRIPTION_FAILED',
      deletedAt: '2024-11-01T00:00:00Z',
      resultsCount: 0,
    },
    {
      id: '5',
      title: 'Top 10 TypeScript Tips You Need to Know',
      url: 'https://youtube.com/watch?v=ghi789',
      thumbnailUrl: 'https://picsum.photos/seed/m5/640/360',
      status: 'completed',
      aiType: 'shorts',
      aspectRatio: '9:16',
      category: 'Education',
      language: 'es',
      provider: 'youtube',
      processStep: 5,
      clipLengths: ['15-30', '30-60'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 2,
    },
  ],
  '2': [
    {
      id: '6',
      title: 'Design System Architecture Deep Dive',
      url: 'https://vimeo.com/123456',
      thumbnailUrl: 'https://picsum.photos/seed/m6/640/360',
      status: 'completed',
      aiType: 'highlights',
      aspectRatio: '16:9',
      category: 'Design',
      language: 'en',
      provider: 'vimeo',
      processStep: 5,
      clipLengths: ['60-120'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 1,
    },
    {
      id: '7',
      title: 'Figma to Code Workflow',
      url: 'https://youtube.com/watch?v=jkl012',
      thumbnailUrl: 'https://picsum.photos/seed/m7/640/360',
      status: 'pending',
      aiType: 'clips',
      aspectRatio: 'auto',
      category: 'Design',
      language: 'pt',
      provider: 'youtube',
      processStep: 0,
      clipLengths: ['30-60'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 0,
    },
  ],
  '3': [
    {
      id: '8',
      title: 'Marketing Digital para Iniciantes',
      url: 'https://youtube.com/watch?v=mno345',
      thumbnailUrl: 'https://picsum.photos/seed/m8/640/360',
      status: 'completed',
      aiType: 'clips',
      aspectRatio: '9:16',
      category: 'Marketing',
      language: 'pt',
      provider: 'youtube',
      processStep: 5,
      clipLengths: ['30-60', '60-90'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 1,
    },
  ],
  '5': [
    {
      id: '9',
      title: 'Kubernetes Production Best Practices',
      url: 'https://youtube.com/watch?v=pqr678',
      thumbnailUrl: 'https://picsum.photos/seed/m9/640/360',
      status: 'completed',
      aiType: 'highlights',
      aspectRatio: '16:9',
      category: 'DevOps',
      language: 'en',
      provider: 'youtube',
      processStep: 5,
      clipLengths: ['60-120', '120-180'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 2,
    },
    {
      id: '10',
      title: 'Docker Compose Multi-Service Setup',
      url: 'https://youtube.com/watch?v=stu901',
      thumbnailUrl: 'https://picsum.photos/seed/m10/640/360',
      status: 'completed',
      aiType: 'shorts',
      aspectRatio: '9:16',
      category: 'DevOps',
      language: 'en',
      provider: 'youtube',
      processStep: 5,
      clipLengths: ['15-30'],
      errorCode: null,
      deletedAt: null,
      resultsCount: 1,
    },
  ],
}

const mockResults: Record<string, MediaResult[]> = {
  '1': [
    {
      id: '101',
      title: 'The 3 Steps to Launch a SaaS',
      description: 'Learn the essential steps to successfully launch your SaaS product.',
      highlightTags: ['saas', 'startup', 'launch', 'business'],
      thumbnailUrl: 'https://picsum.photos/seed/r1/360/640',
      viralityScore: 92,
      projectVersion: 2,
      renderingStatus: 'completed',
    },
    {
      id: '102',
      title: 'Why Most SaaS Fail',
      description: 'Common mistakes that lead to SaaS failure and how to avoid them.',
      highlightTags: ['saas', 'failure', 'lessons'],
      thumbnailUrl: 'https://picsum.photos/seed/r2/360/640',
      viralityScore: 85,
      projectVersion: 1,
      renderingStatus: 'completed',
    },
    {
      id: '103',
      title: 'Pricing Strategy for SaaS',
      description: 'How to price your SaaS product effectively for maximum revenue.',
      highlightTags: ['pricing', 'saas', 'revenue'],
      thumbnailUrl: 'https://picsum.photos/seed/r3/360/640',
      viralityScore: 78,
      projectVersion: 1,
      renderingStatus: 'pending',
    },
    {
      id: '104',
      title: 'Tech Stack for Your SaaS',
      description: null,
      highlightTags: ['techstack', 'development'],
      thumbnailUrl: 'https://picsum.photos/seed/r4/640/360',
      viralityScore: 65,
      projectVersion: 0,
      renderingStatus: 'pending',
    },
    {
      id: '105',
      title: 'Customer Acquisition Tips',
      description: 'Proven strategies to acquire your first 100 customers.',
      highlightTags: ['marketing', 'customers', 'growth'],
      thumbnailUrl: 'https://picsum.photos/seed/r5/360/640',
      viralityScore: 88,
      projectVersion: 2,
      renderingStatus: 'completed',
    },
    {
      id: '106',
      title: 'Building an MVP Fast',
      description: 'How to build a minimum viable product in just 2 weeks.',
      highlightTags: ['mvp', 'startup', 'agile'],
      thumbnailUrl: 'https://picsum.photos/seed/r6/360/640',
      viralityScore: 71,
      projectVersion: 1,
      renderingStatus: 'completed',
    },
    {
      id: '107',
      title: 'Scaling Infrastructure',
      description: 'When and how to scale your SaaS infrastructure.',
      highlightTags: ['scaling', 'infrastructure'],
      thumbnailUrl: 'https://picsum.photos/seed/r7/360/640',
      viralityScore: 55,
      projectVersion: 1,
      renderingStatus: 'failed',
    },
    {
      id: '108',
      title: 'Fundraising for SaaS',
      description: 'How to raise funding for your SaaS startup.',
      highlightTags: ['fundraising', 'vc', 'startup', 'investment'],
      thumbnailUrl: 'https://picsum.photos/seed/r8/360/640',
      viralityScore: 95,
      projectVersion: 3,
      renderingStatus: 'completed',
    },
  ],
  '2': [
    {
      id: '201',
      title: 'AI Will Change Everything',
      description: 'The most impactful prediction about AI from our expert panel.',
      highlightTags: ['ai', 'future', 'technology'],
      thumbnailUrl: 'https://picsum.photos/seed/r9/360/640',
      viralityScore: 94,
      projectVersion: 2,
      renderingStatus: 'completed',
    },
    {
      id: '202',
      title: 'The Ethics of AI Development',
      description: 'Important ethical considerations when building AI systems.',
      highlightTags: ['aiethics', 'responsible'],
      thumbnailUrl: 'https://picsum.photos/seed/r10/360/640',
      viralityScore: 82,
      projectVersion: 1,
      renderingStatus: 'completed',
    },
    {
      id: '203',
      title: 'AI Tools for Developers',
      description: 'The best AI-powered tools every developer should be using.',
      highlightTags: ['aitools', 'developer', 'productivity'],
      thumbnailUrl: 'https://picsum.photos/seed/r11/360/640',
      viralityScore: 76,
      projectVersion: 1,
      renderingStatus: 'rendering',
    },
  ],
  '5': [
    {
      id: '501',
      title: 'Type Guards Explained',
      description: 'Master TypeScript type guards with practical examples.',
      highlightTags: ['typescript', 'typeguards'],
      thumbnailUrl: 'https://picsum.photos/seed/r12/360/640',
      viralityScore: 89,
      projectVersion: 1,
      renderingStatus: 'completed',
    },
    {
      id: '502',
      title: 'Generic Types Made Simple',
      description: 'Understanding TypeScript generics doesn\'t have to be hard.',
      highlightTags: ['typescript', 'generics', 'tips'],
      thumbnailUrl: 'https://picsum.photos/seed/r13/360/640',
      viralityScore: 91,
      projectVersion: 2,
      renderingStatus: 'completed',
    },
  ],
  '6': [
    {
      id: '601',
      title: 'Token Architecture',
      description: 'How to structure design tokens for maximum flexibility.',
      highlightTags: ['designsystem', 'tokens'],
      thumbnailUrl: 'https://picsum.photos/seed/r14/360/640',
      viralityScore: 87,
      projectVersion: 1,
      renderingStatus: 'completed',
    },
  ],
  '8': [
    {
      id: '801',
      title: 'O Que é Marketing Digital?',
      description: 'Introdução completa ao marketing digital para quem está começando.',
      highlightTags: ['marketingdigital', 'iniciantes'],
      thumbnailUrl: 'https://picsum.photos/seed/r15/360/640',
      viralityScore: 80,
      projectVersion: 1,
      renderingStatus: 'completed',
    },
  ],
  '9': [
    {
      id: '901',
      title: 'Pod Security Standards',
      description: 'Essential Kubernetes pod security standards you need to implement.',
      highlightTags: ['kubernetes', 'security', 'devops'],
      thumbnailUrl: 'https://picsum.photos/seed/r16/360/640',
      viralityScore: 93,
      projectVersion: 2,
      renderingStatus: 'completed',
    },
    {
      id: '902',
      title: 'Resource Limits Best Practices',
      description: 'Setting proper resource limits and requests in Kubernetes.',
      highlightTags: ['kubernetes', 'resources'],
      thumbnailUrl: 'https://picsum.photos/seed/r17/360/640',
      viralityScore: 86,
      projectVersion: 1,
      renderingStatus: 'completed',
    },
  ],
  '10': [
    {
      id: '1001',
      title: 'Docker Networking Explained',
      description: 'How Docker Compose networking works under the hood.',
      highlightTags: ['docker', 'networking'],
      thumbnailUrl: 'https://picsum.photos/seed/r18/360/640',
      viralityScore: 74,
      projectVersion: 1,
      renderingStatus: 'completed',
    },
  ],
}

export function useAdminUserMedia(userId: string, enabled: boolean) {
  return useQuery({
    queryKey: adminMediaKeys.user(userId),
    queryFn: async () => {
      await new Promise((r) => setTimeout(r, 400))
      return mockMedia[userId] ?? []
    },
    enabled,
  })
}

export function useAdminMediaResults(mediaId: string, enabled: boolean) {
  return useQuery({
    queryKey: adminMediaKeys.results(mediaId),
    queryFn: async () => {
      await new Promise((r) => setTimeout(r, 300))
      return mockResults[mediaId] ?? []
    },
    enabled,
  })
}
