/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppRevenueRouteImport } from './routes/_app/revenue'
import { Route as AppProvidersRouteImport } from './routes/_app/providers'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'
import { Route as AppBusinessUsersRouteImport } from './routes/_app/business/users'
import { Route as AppBusinessCompaniesRouteImport } from './routes/_app/business/companies'
import { Route as AppBusinessCompaniesCompanyIdRouteImport } from './routes/_app/business/companies.$companyId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppBusinessUsersRoute = AppBusinessUsersRouteImport.update({
  id: '/business/users',
  path: '/business/users',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessCompaniesRoute = AppBusinessCompaniesRouteImport.update({
  id: '/business/companies',
  path: '/business/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessCompaniesCompanyIdRoute =
  AppBusinessCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AppBusinessCompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/profile': typeof AppProfileRoute
  '/providers': typeof AppProvidersRoute
  '/revenue': typeof AppRevenueRoute
  '/teams': typeof AppTeamsRouteWithChildren
  '/business/companies': typeof AppBusinessCompaniesRouteWithChildren
  '/business/users': typeof AppBusinessUsersRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/business/companies/$companyId': typeof AppBusinessCompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/profile': typeof AppProfileRoute
  '/providers': typeof AppProvidersRoute
  '/revenue': typeof AppRevenueRoute
  '/': typeof AppIndexRoute
  '/business/companies': typeof AppBusinessCompaniesRouteWithChildren
  '/business/users': typeof AppBusinessUsersRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/teams': typeof AppTeamsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/business/companies/$companyId': typeof AppBusinessCompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/providers': typeof AppProvidersRoute
  '/_app/revenue': typeof AppRevenueRoute
  '/_app/teams': typeof AppTeamsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/business/companies': typeof AppBusinessCompaniesRouteWithChildren
  '/_app/business/users': typeof AppBusinessUsersRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/business/companies/$companyId': typeof AppBusinessCompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/finance'
    | '/profile'
    | '/providers'
    | '/revenue'
    | '/teams'
    | '/business/companies'
    | '/business/users'
    | '/teams/$teamId'
    | '/users/$userId'
    | '/teams/'
    | '/users/'
    | '/business/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/finance'
    | '/profile'
    | '/providers'
    | '/revenue'
    | '/'
    | '/business/companies'
    | '/business/users'
    | '/teams/$teamId'
    | '/users/$userId'
    | '/teams'
    | '/users'
    | '/business/companies/$companyId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/finance'
    | '/_app/profile'
    | '/_app/providers'
    | '/_app/revenue'
    | '/_app/teams'
    | '/_app/'
    | '/_app/business/companies'
    | '/_app/business/users'
    | '/_app/teams/$teamId'
    | '/_app/users/$userId'
    | '/_app/teams/'
    | '/_app/users/'
    | '/_app/business/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revenue': {
      id: '/_app/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/business/users': {
      id: '/_app/business/users'
      path: '/business/users'
      fullPath: '/business/users'
      preLoaderRoute: typeof AppBusinessUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/companies': {
      id: '/_app/business/companies'
      path: '/business/companies'
      fullPath: '/business/companies'
      preLoaderRoute: typeof AppBusinessCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/companies/$companyId': {
      id: '/_app/business/companies/$companyId'
      path: '/$companyId'
      fullPath: '/business/companies/$companyId'
      preLoaderRoute: typeof AppBusinessCompaniesCompanyIdRouteImport
      parentRoute: typeof AppBusinessCompaniesRoute
    }
  }
}

interface AppTeamsRouteChildren {
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
}

const AppTeamsRouteChildren: AppTeamsRouteChildren = {
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
}

const AppTeamsRouteWithChildren = AppTeamsRoute._addFileChildren(
  AppTeamsRouteChildren,
)

interface AppBusinessCompaniesRouteChildren {
  AppBusinessCompaniesCompanyIdRoute: typeof AppBusinessCompaniesCompanyIdRoute
}

const AppBusinessCompaniesRouteChildren: AppBusinessCompaniesRouteChildren = {
  AppBusinessCompaniesCompanyIdRoute: AppBusinessCompaniesCompanyIdRoute,
}

const AppBusinessCompaniesRouteWithChildren =
  AppBusinessCompaniesRoute._addFileChildren(AppBusinessCompaniesRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppTeamsRoute: typeof AppTeamsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppBusinessCompaniesRoute: typeof AppBusinessCompaniesRouteWithChildren
  AppBusinessUsersRoute: typeof AppBusinessUsersRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppProfileRoute: AppProfileRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppTeamsRoute: AppTeamsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppBusinessCompaniesRoute: AppBusinessCompaniesRouteWithChildren,
  AppBusinessUsersRoute: AppBusinessUsersRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
